name: CI/CD Pipeline

# Jalankan pipeline setiap kali ada push ke branch main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Docker untuk digunakan dalam job ini
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login ke DockerHub menggunakan secrets
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build image Docker dan tag dengan 'latest'
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weight-advisor:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/weight-advisor:latest

      # Verifikasi bahwa image telah didorong ke DockerHub
      - name: Verify DockerHub push
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weight-advisor:latest
